# Generated by Django 3.1 on 2020-09-21 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0008_siteinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Required Date')),
                ('size', models.TextField(blank=True, null=True, verbose_name='Size and Measurments')),
                ('extra_items', models.TextField(blank=True, null=True, verbose_name='Additional Items')),
                ('custom_details', models.TextField(blank=True, null=True, verbose_name='Customization Details')),
                ('materials', models.TextField(blank=True, null=True, verbose_name='Materials and Fabrics')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
