# Generated by Django 3.0.5 on 2020-09-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20200921_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customorder',
            name='date',
            field=models.DateField(help_text='2020-01-01', verbose_name='Required Date'),
        ),
    ]
