# Generated by Django 3.0.5 on 2020-09-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20200923_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customorder',
            name='date',
            field=models.DateField(error_messages={'required': 'Incorrect Date Format'}, help_text='Format: 2020-01-01', verbose_name='Required Date'),
        ),
    ]
