# Generated by Django 3.0.5 on 2020-09-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20200930_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='delivery_status',
            field=models.CharField(blank=True, default='pending', max_length=200, null=True),
        ),
    ]
