# Generated by Django 3.0.5 on 2020-10-07 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='stock',
            field=models.IntegerField(null=True),
        ),
    ]
