# Generated by Django 3.0.5 on 2020-10-07 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_token_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='valid',
            field=models.BooleanField(default=True),
        ),
    ]
