# Generated by Django 3.0.5 on 2020-10-07 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20201007_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='token',
            old_name='token',
            new_name='code',
        ),
    ]
