# Generated by Django 3.0.5 on 2020-10-07 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20201007_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='code',
            field=models.BooleanField(default=False),
        ),
    ]
