# Generated by Django 3.0.5 on 2020-10-07 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_orderitem_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='finalTotal',
            field=models.FloatField(default=0),
        ),
    ]
