# Generated by Django 3.0.5 on 2020-10-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_auto_20201007_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercontactmanager',
            name='seen',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
