# Generated by Django 3.0.5 on 2020-10-11 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_customercontactmanager_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
