# Generated by Django 3.0.5 on 2020-10-13 02:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_auto_20201011_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='about',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
