# Generated by Django 3.0.5 on 2020-10-13 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_auto_20201013_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
